src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/partials/header.html.twig
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="#">Evaldas Task</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">


          {% if app.user %}	

          <li class="nav-item active">
            <a class="nav-link" href="{{ path('dashboard') }}">Home <span class="sr-only">(current)</span></a>
          </li>

		  {% if is_granted('ROLE_ADMIN') %}
	          <li class="nav-item">
	            <a class="nav-link" href="{{ path('color') }}">Color</a>
	          </li>
	          <li class="nav-item">
	            <a class="nav-link" href="{{ path('move') }}">Moves</a>
	          </li>
	          <li class="nav-item">
	            <a class="nav-link" href="{{ path('side') }}">Sides</a>
	          </li> 
            <li class="nav-item">
              <a class="nav-link" href="{{ path('users') }}">Users</a>
            </li>         
	          
          {% endif %}

            <li class="nav-item">
              <a class="nav-link" href="{{ path('orders') }}">Orders</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('app_logout') }}">({{ app.user.username }}) Logout</a>
            </li>

          {% else %}
 		  <li class="nav-item">
            <a class="nav-link" href="{{ path('app_login') }}">Login</a>
          </li>
          {% endif %} 	  
        </ul>

        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

templates/partials/paginate.html.twig
{% if totalPage > 1 %}
<ul class="pagination pagination-sm">
    {# `«` arrow  #}
    <li {{ currentPage == 1 ? 'class="disabled"' }}>
        <a href="{{ path('orders', {page: currentPage-1 < 1 ? 1 : currentPage-1}) }}">«</a>
    </li>

    {# Render each page number #}
    {% for i in 1..totalPage %}
    <li {{ currentPage == i ? 'class="active"' }}>
    <a href="{{ path('orders', {page: i}) }}">{{ i }}</a>
    </li>
    {% endfor %}

    {# `»` arrow #}
    <li {{ currentPage == totalPage ? 'class="disabled"' }}>
        <a href="{{ path('orders', {page: currentPage+1 <= totalPage ? currentPage+1 : currentPage}) }}">»</a>
    </li>
</ul>
{% endif %}